### ISSUE TITLE
The plugin 'White Space Terminator' could not be loaded

### ISSUE THREAD

**Issue by yanickrochon** [Kozea/Gedit-WhiteSpace-Terminator#1]
The message I am getting is :

```
An error occured: Plugin loader 'python3' was not found
```

Naturally, I fired up a terminal and did a

```
$ sudo apt-get install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

It worked before, and I've been busy and did not use this install for a while, so I can't remember _when_ was the last time it worked and what I've been doing since then. Anyhow, any chance I can actually get a better error message or you might know how to fix this?

BTW: I did overwrite the files in `~/.local/share/gedit/plugins`

**Comment by raelgc** [comment]
Open the .plugin file and replace `Loader=python3` by `Loader=python`

**Comment by yanickrochon** [comment]
Thanks. I forgot about that question. While I'm sure it may be a solution, I did manage to solve this problem at some point otherwise. I'm usually more proactive when it comes to questions that I ask, especially when I find the answer myself meanwhile...
